### ISSUE TITLE
新help

### ISSUE THREAD

**Issue by yaakiyu** [free-RT/sakura-bot#61]
helpつかいにくい。
なので、新しいhelpの作り方を模索する。
今のところjsonで管理しようかと思ってる。
そのほうがやりやすいんだよね。

**Comment by ysmreg** [comment]
確かにjsonのほうがわかりやすいかもです。現在はcommandのdocを読み込んで解析していますが、jsonであればコードも簡単でhelpも編集しやすそうです

**Comment by yaakiyu** [comment]
jsonは直接エディタで日本語を書きにくいから
data/sakurabadge.pyみたいにpythonの辞書にしちゃうか

**Comment by ysmreg** [comment]
それがいいかもですね

**Comment by yaakiyu** [comment]
新Helpシステム作成完了。
